package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new io.flutter.plugins.camera.CameraPlugin());
    } catch (Exception e) {
      System.err.println("Error registering plugin camera_android: " + e.getMessage());
    }
    try {
      flutterEngine.getPlugins().add(new com.hugocornellier.face_detection_tflite.FaceDetectionTflitePlugin());
    } catch (Exception e) {
      System.err.println("Error registering plugin face_detection_tflite: " + e.getMessage());
    }
    try {
      flutterEngine.getPlugins().add(new com.mr.flutter.plugin.filepicker.FilePickerPlugin());
    } catch (Exception e) {
      System.err.println("Error registering plugin file_picker: " + e.getMessage());
    }
    try {
      flutterEngine.getPlugins().add(new com.hugocornellier.flutter_litert.FlutterLitertPlugin());
    } catch (Exception e) {
      System.err.println("Error registering plugin flutter_litert: " + e.getMessage());
    }
    try {
      flutterEngine.getPlugins().add(new io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin());
    } catch (Exception e) {
      System.err.println("Error registering plugin flutter_plugin_android_lifecycle: " + e.getMessage());
    }
    try {
      flutterEngine.getPlugins().add(new io.flutter.plugins.imagepicker.ImagePickerPlugin());
    } catch (Exception e) {
      System.err.println("Error registering plugin image_picker_android: " + e.getMessage());
    }
    try {
      flutterEngine.getPlugins().add(new com.github.dart_lang.jni.JniPlugin());
    } catch (Exception e) {
      System.err.println("Error registering plugin jni: " + e.getMessage());
    }
    try {
      flutterEngine.getPlugins().add(new com.github.dart_lang.jni_flutter.JniFlutterPlugin());
    } catch (Exception e) {
      System.err.println("Error registering plugin jni_flutter: " + e.getMessage());
    }
    try {
      flutterEngine.getPlugins().add(new io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin());
    } catch (Exception e) {
      System.err.println("Error registering plugin shared_preferences_android: " + e.getMessage());
    }
    try {
      flutterEngine.getPlugins().add(new com.tekartik.sqflite.SqflitePlugin());
    } catch (Exception e) {
      System.err.println("Error registering plugin sqflite_android: " + e.getMessage());
    }
  }
}
